pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t adhitya-portfolio .'
            }
        }
        stage('Create and run Docker Container'){
            steps{
                bat 'docker run -d --name portfolioCont -p 8081:80 adhitya-portfolio'
            }
        }

    }
}